import = [
    # "/home/uit/.config/alacritty/themes/dracula.toml",
    "/home/uit/.config/alacritty/themes/catppuccin-mocha.toml",
]

[colors]
draw_bold_text_with_bright_colors = true

[cursor.style]
shape = "Underline"

[cursor.vi_mode_style]
shape = "Block"

[font]
size = 14

[font.bold]
family = "JetBrainsMono NF"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono NF"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono NF"
style = "Italic"

[font.normal]
family = "JetBrainsMono NF"
style = "Regular"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false

[shell]
program = "/usr/bin/zsh"

[window]
opacity = 0.8

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 20
